#!/bin/sh

usage () {
 echo "Usage: $0 domain [...]"
 exit 1
}

BRANCH="$(date +'%Y%m%d-%H%M%S-batch')"

cleaning () {
	git checkout develop
	git branch -d "${BRANCH}"
}

trap cleaning 0 1 2 3 4 5 6 7 8 9 10 15

if [ "x$1" = "x" ]; then
 usage
fi

git checkout develop
git checkout -b ${BRANCH} 

while [ ! "x$1" = "x" ]; do
 D=$1
 echo "$D" | grep -q "^\."
 if [ ! $? = 0 ]; then
  D=".${D}"
 fi
 echo "$D" | grep $(cat blackhost.txt | sed -e 's;^;-e ;')
 if [ ! $? = 0 ]; then
   echo "ドメイン $D はすでにある設定で該当するため無視します" >/dev/stderr
   continue
 fi
 echo "$D" >> blackhost.txt && \
 make sort 
 ./check
 if [ $? = 0 ]; then
  git add blackhost.txt
 else
  git checkout blackhost.txt
	echo "REVERTED DOMAIN $D" > /dev/stderr
 fi
 shift
done
git commit -m "batch commit" && \
git checkout develop && git merge "${BRANCH}" && \
git checkout master && git merge develop
