#!/bin/sh

usage () {
 echo "Usage: $0 domain [...]"
 exit 1
}

BRANCH="$(date +'%Y%m%d-%H%M%S-batch')"

cleaning () {
	git checkout develop
	git branch -d "${BRANCH}"
}

if [ "x$1" = "x" ]; then
 usage
fi

git checkout develop
git checkout -b ${BRANCH} 

while [ ! "x$1" = "x" ]; do
 D=$1
 echo "$D" | grep -q "^\."
 if [ ! $? = 0 ]; then
  D=".${D}"
 fi
 echo "$D" >> blackhost.txt && \
 make sort && git commit -m "batch commit" && \
 git checkout develop && git merge --ff-only "${BRANCH}" && \
 git checkout master && git merge --ff-only develop 


