#!/bin/bash

IMAGE=squidcheck

docker inspect $IMAGE >& /dev/null
if [ ! $? = 0 ]; then
  docker build -t $IMAGE .
	if [ ! $? = 0 ]; then
	  echo "イメージ作成に失敗しています、確認して下さい" > /dev/stderr
		exit 1
  fi
fi

echo "--- check black/white list ---"
echo '※ "no running copy"の出力は正常です'
docker run -m 128m  --memory-swap=256m -v `pwd`:/vagrant --rm $IMAGE
echo "------------------------------"
